server:
  port: 8082
  context-path: /

spring:
  application:
    name: addressbook-service
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://106.75.213.54:33037/lhl?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: yuexun123
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.pxl.addressbook.entity
  mapperLocations: classpath:com/pxl/addressbook/mapperxml/*.xml
