spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

logging:
  level:
    org:
      springframework:
        cloud:
          alibaba:
            seata:
              web: info

logging:
  level:
    io:
      seata: info